### PR TITLE
pixelformats: Add checkerboard background

### PR DESCRIPTION
**Pull request by thedmd**

### CODE REVIEW

**Comment by bwrsandman** [comment]
Checkerboard is expected to always be valid right?
The check is necessary for the format textures because we skip some but I don't think it is necessary for the checkerboard.

**Comment by bwrsandman** [comment]
With the checker board you can probably remove the portion of the hsv colour wheel that sets alpha. Leave the gradient block though.

Or you can try the inverse and keep the alpha portion but keep the v value constant. 

Try it out and tell me what you think.

The issue is minor but there's a weird look due to alpha and the v value decreasing at the same rate.

**Comment by thedmd** [comment]
> Checkerboard is expected to always be valid right?

Usually. I checked because lack of background is a bit better than potential crash. : )

> With the checker board you can probably remove the portion of the hsv colour wheel that sets alpha. Leave the gradient block though.

`pixel[3] = 1.0f - distance;` do you have this line in mind?

pixel[3] = 1.0f - distance;

**Comment by bwrsandman** [comment]
> do you have this line in mind? 

Yes. It might look like garbage so you tell me which is better.
There's just a darkening right now as alpha decreases that doesn't really reflect how blending works and could be distracting.

**Comment by thedmd** [comment]
This is what I got with `v == 1.0f`. Black rim is gone, which is a plus.

image

**Comment by bwrsandman** [comment]
Is that better or worse? Are we losing information?
Also try without setting alpha. My fear with that one is that it's too small to see the checkerboard

**Comment by bwrsandman** [comment]
Ahh also, the green in the full colour squares is now blending with the colour wheel. I actually prefer how it was before. 😅

**Comment by thedmd** [comment]
Loosing information? I don't think so. With alpha set to 1, this tiny gradient isn't enough to make changes visible.

Now A8 is not ideal example. : )

image

**Comment by bwrsandman** [comment]
Okay. My preference is the way it is.

**Comment by bwrsandman** [comment]
RGB8S loses a lot of information without the v value

**Comment by thedmd** [comment]
I put checkbox to ignore alpha channel (just disable blending).

Preview for textures with transparency look better with `v == 1`.

It is not ideal right now, but will help to find differences between APIs.

image

**Pull request merged**
